// Auto-generated by docs integration - DO NOT EDIT
export const generatedRegistry = {
  'basics': {
    content: import.meta.glob('../docs/basics/**/*.{md,mdx}', { eager: true }),
    toc: import.meta.glob('../docs/basics/**/_toc.ts', { eager: true }),
  },
  'concurrency': {
    content: import.meta.glob('../docs/concurrency/**/*.{md,mdx}', { eager: true }),
    toc: import.meta.glob('../docs/concurrency/**/_toc.ts', { eager: true }),
  },
  'generics': {
    content: import.meta.glob('../docs/generics/**/*.{md,mdx}', { eager: true }),
    toc: import.meta.glob('../docs/generics/**/_toc.ts', { eager: true }),
  },
  'url-shortener': {
    content: import.meta.glob('../docs/url-shortener/**/*.{md,mdx}', { eager: true }),
    toc: import.meta.glob('../docs/url-shortener/**/_toc.ts', { eager: true }),
  }
}
